mutation createPost(
  $title:String!,
  $description:String!,
  $url:String!, 
  $companyName:String, 
  $street:String!,
  $city:String!,
  $state:String!,
  $country:String!,
  $zipCode:String!
) {
  createPost(
    title: $title
    description: $description
    url: $url
    companyName: $companyName 
    address: {
      street: $street
      city: $city"
      state: $state
      country: $country
      zipCode: $zipCode
    }
  ) {
    id
    title
    description
    companyName
    address {
      street
    }
  }
}
